### ISSUE TITLE
Implement HTTP announce library

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1108]
The `dagsync/dtsync` package includes announcement over gossipsub, but the HTTP favour at `dagsync/httpsync` only offers publication of advertisements. 

There is a separate `announce` package which seems to only include functionality for the receiving side. 

Ideally `dagsync` packages should offer consistent functionality; the only missing bit just now is explicit announce over HTTP.

**Comment by gammazero** [comment]
I do not think HTTP announce messages are a function of the httpsync publisher, and I do not think that gossipsub announce messages are a function of the dtsync publisher.  Both publisher types should be able to publish announce messages over HTTP, to send direct messages to specific indexer(s), or over gossipsub,  to broadcasting announce messages to all interested indexers.

I think it would be more correct to make the announce publishers (HttpAnnouncer and PubsubAnnouncer) into separate packages and let the dtsync and httpsync publishers instantiate them as configured.

**Comment by masih** [comment]
However we want to slice and dice this we should have the ability to make direct http announcements. 

As for behaviour between dtsync and httpsync, it seems odd that one doesn't make an announcement at all while the other does. 

Announcing is part of IPNI spec and should be included. I personally care less about making every transport permutations of publish vs announcement configurable and more about consistent interactions at systems level regardless of transport.
