### ISSUE TITLE
Check addrs in extended providers are not empty before updating registry

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1152]
We should check that if extended providers are set, only update registry if their address is not empty. The [check](https://github.com/ipni/storetheindex/blob/55f942d8368484bf6183e09f967db183f4295910/internal/registry/registry.go#L666) exists already for top level addrs but not for [extended providers](https://github.com/ipni/storetheindex/blob/55f942d8368484bf6183e09f967db183f4295910/internal/registry/registry.go#L671).

**Comment by gammazero** [comment]
I thought is was allowed for the extended providers to have empty addresses, as that would mean to use the provider's addresses, similar to how the extended provider metadata [can be empty](https://github.com/ipni/storetheindex/blob/55f942d8368484bf6183e09f967db183f4295910/internal/registry/registry.go#L119-L121). 

@ischasny Is an extended provider allowed to have empty addresses (meaning use the provider's), or is that an error?

**Comment by ischasny** [comment]
I think addresses can be empty for the main provider but not for anyone else. From the spec:
```
The Provider from the encapsulating advertisement must be present in the Providers of the ExtendedProvider object, and must sign in this way as well. It may omit Metadata and Addresses if they match the values already set at the encapsulating advertisement. However, Signature must be present.
```
