### ISSUE TITLE
Add metrics: add and remove multihashes

### ISSUE THREAD

**Issue by davidd8** [ipni/storetheindex#116]
Add the following metric counters:
- ingest_add_multihash
- ingest_remove_multihash

This will help breakdown announcement requests to understand index providing patterns.

**Comment by gammazero** [comment]
Are these counts for every individual multihash added and removed, or counts of the advertisements that are adding or removing multihash indexes?

If this is counting individual multihashes removed, this will need to be part of a compaction implementation.  Indexes are removed in bulk by deleting the metadata (identified by context ID).  There is no mapping from the metadata/contextID back to each multihash.  The multihashes are not actually removed until they are queried and the indexer sees that they no longer have a metadata.  A background compaction implementation could iterate through multihashes and remove dead ones, and adjust the counter then.

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
