### ISSUE TITLE
Deploy a new indexer node on dev to populate `dhstore`

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1162]
Deploy a new storetheindex instance that:
* does not persist unencrypted processed index records.
  * instead, sends them to `dhstore`.
* keeps a copy of all ingested ads for mirroring purposes on a separate PVC volume.
* has metrics enabled to get an accurate count of the number of CIDs ingested.
* ingests from the begining by importing all providers from `cid.contact`.

**Comment by ischasny** [comment]
Other related PRs:
https://github.com/ipni/storetheindex/pull/1191
https://github.com/ipni/storetheindex/pull/1189

**Comment by ischasny** [comment]
Closing as it was done and verified
