### ISSUE TITLE
Add libp2p implementation for double hashed client

### ISSUE THREAD

**Issue by ischasny** [ipni/storetheindex#1207]
Currently there is only [HTTP implementation](https://github.com/ipni/storetheindex/blob/main/api/v0/finder/client/http/dhash_client.go) for the double hashed client. Add libp2p implementation alongside the existing [libp2p client](https://github.com/ipni/storetheindex/tree/main/api/v0/finder/client/libp2p).

**Comment by gammazero** [comment]
The libp2p client has been removed for the find client, so no need to implement it for dh client.
