### ISSUE TITLE
Consider moving away from `gorilla/mux` for request handing

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1212]
The HTTP server implementations in this repo use `gorilla/mux` framework, which [has been archived since late 2022](https://github.com/gorilla#gorilla-toolkit).  Consider moving away from the framework.

I recommend using the vanilla go `http` package considering the APIs offered by storetheindex are simple enough.

**Comment by gammazero** [comment]
Using the default `http` package means implementing user parameter handling to handle things like routes like: `"/cid/{cid}"`.  This is not a big issue, but something to consider when there are many routers that already handle it.

For a simple replacement, consider [httprouter](https://github.com/julienschmidt/httprouter) which has been around a long time.

For high performance, consider [fasthttp/router](https://github.com/fasthttp/router) with [fasthttp](https://github.com/valyala/fasthttp)

**Comment by masih** [comment]
Path parameter handling is done with the default go SDK in indexstar; I honestly don't find it to be that verbose nor cumbersome.

**Comment by gammazero** [comment]
👍 
Looks like there is no complex path handling to worry about, and generally one should use the standard go `http` package unless there is a specific reason not to.
