### ISSUE TITLE
Get a random mh+provider record

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#1258]
It would be useful for random validations to be able to get a random provider record.
a user could then know that given the current advert chain head for that provider and that random record that they could walk the advert chain and re-confirm that the provider was at that point claiming they had that piece of content.

**Comment by willscott** [comment]
if you get a hash from the latest ad you're biasing towards never sampling older CIDs - do we care only about the most recent content, or also content that's been advertised for a while?

**Comment by ischasny** [comment]
Agree, but you can walk back the chain to some depth and grab a cid from there? Pulling an ad without listing cids is relatively fast.

**Comment by willscott** [comment]
yep, this is also possible - i guess my only thought is that if we have e.g. a .storage like provider with millions of ads, are we really going to want to walk a million ads on each client request for a random CID?

**Comment by gammazero** [comment]
Picking a random sample requires a set to choose from. If we want to be able to choose old samples, then that requires keeping those somewhere, resulting in an ever-increasing pool if we keep an even distribution across all indexing. Or, we have to be able to walk back to ever-increasing depths in ad chains.  There is another way...

Proposal: Use the content mirror and choose a random CAR file and pull multihashes from that.

**Comment by gammazero** [comment]
When the indexer writes multihashes to its value-store, it logs the first multihash with the publisher/provider and ad cid.  This  serves as a way to collect random samples to test with.  Here is an example of a log entry:
```
{"level":"info","ts":"2023-07-13T21:47:30.373Z","logger":"indexer/ingest","caller":"ingest/linksystem.go:686","msg":"Indexed multihashes from chunk","publisher":"12D3KooWGNhtyrc99xvVqemiZufyBAgAv2RP6KLi5SrN2AZzB9Xy","adCid":"baguqeerazvpelk5gi6ct7pmiwmf3zn73vzrdfeifgunbbfews3a5jz7vn7ja","contextID":"AXESILrxg6roaqUm4yeRoWb5+WtsFh7AOWQCmiZoxKG4ki+B","entriesKind":"CarEntryChunk","multihashes":508,"sample":"QmbDKWy4yf1eXYKHe8ypDSfHRn5aEHxCGMro7FgMNh6hnB"}
```

Searching for the string "sample" will yield random multihashes and the publishers/providers.

@willscott If this is sufficient, please close issue.

**Comment by willscott** [comment]
I think this issue is to track being able to have a client-facing API for getting a random multihash, rather than for the indexer itself to find examples for testing

**Comment by gammazero** [comment]
You can use the `random` command from version v0.1.4 of the ipni-cli to do this.

Here is a complete command that selects a random provider, random advertisement, and random multihash:
```shell
ipni provider -i https://cid.contact --all --error --invert --id-only | xargs shuf -n1 -e | ipni random -i https://cid.contact --n=5 --m=1 --quiet | xargs -J % -n1 ipni find -i https://cid.contact -mh %
```
Let's break that down...

The first part,
```shell
ipni provider -i https://cid.contact --all --error --invert --id-only 
```
outputs the provider ID (`--id-only`) of all providers (`--all`) that do not have a LastError (`--error --invert`).

The second part,
```shell
xargs shuf -n1 -e
```
selects 1 of the provider IDs given as input end echos that to output

The third part,
```shell
ipni random -i https://cid.contact --n=5 --m=1 --quiet
```
selects a random suitable* advertisement from the provider (ID from stdin) from the latest 5 ads (`--n=5`) and then selects 1 (`--m=1`) random multihash from the first entries block, and outputs only that multihash (`--quiet`).

* suitable means the advertise is not a removal advertisement and has content that has not been removed by a removal advertisement later in the ad chain.

The fourth part,
```shell
xargs -J % -n1 ipni find -i https://cid.contact -mh %
```
uses `ipni find` to lookup the provider info for the random multihash

**Comment by gammazero** [comment]
Closing as this can be done using cli: https://github.com/ipni/ipni-cli/blob/main/doc/random-mh-lookup.md
