### ISSUE TITLE
Getting a 403 response from dev.cid.contact

### ISSUE THREAD

**Issue by TorfinnOlsen** [ipni/storetheindex#1288]
When attempting to resolve to https://dev.cid.contact receiving a 403 response from the gateway.

https://dev.cid.contact/

403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: KXC0UqN_O3EFVYUFS1txQ2EV9ILcGe0BVUZMVvsdsCazeg4HEqI8xQ==

First reported by Muhammad Arslan @thebeard on slack 12:36pm PST 02/20/23 

https://filecoinproject.slack.com/archives/C02T827T9N0/p1676925391520659

Troubleshooting steps taken so far:

I attempted to duplicate the issue from my machine and got the same response.

**Comment by masih** [comment]
Issue was with the landing page only and restored by https://github.com/ipni/storetheindex/pull/1289

Root cause likely due to chagnes introduced as part of latest commits to indexstar.

**Comment by masih** [comment]
OK found the root cause: missing `--` [here](https://github.com/ipni/storetheindex/pull/1287/files#diff-156b774367c6c61a79fd0f40da094a9d7fa96c50f209b613d576bbb65736197cR16)
