### ISSUE TITLE
Separate ad download workers from ingest workers

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1504]
This is a double edge sword because it impacts both fetching advertisements _and_ processing them.

Reducing it means less write parallelism but also potentially slower ad chain download.

We should engineer a tuning knob to offer individual control for each, considering one is disk IO bound and the other is network latency bound.

Cc @gammazero

_Originally posted by @masih in https://github.com/ipni/storetheindex/pull/1503#discussion_r1154234412_

**Comment by gammazero** [comment]
The question then becomes how we want to balance this.  How many goroutines/cpu/time to allocate to ad chain fetching vs ad processing? If we split this up, then ad processors will be idle until at least one whole ad chain is fetched.

I would keep these combined and prioritize ad processing. This way all resources can be used to fetch ad chains until there are ads to process. Once there are ads to process, then any workers that are done with a chain can work on processing ads before reading another chain.

**Comment by gammazero** [comment]
The number of goroutines that download advertisement chains is limited to 1 per publisher. There can be any number of concurrent ad chain downloads as long as they are for different publishers. These are not limited by the number of workers.

**Comment by gammazero** [comment]
A problem with having separate download workers is that they download ad chains faster than those chains can be processed. This means that all the ad chains need to be temporarily stored until they can be processed, which may take up excessive space. It also means that the indexer will use resources to continue downloading ad chains, even though they will not be processed for some time, and likely will be replaced by newer chains before processing can be done.  This is wasteful.

It is better to be able to queue a limited number of ad chains while all workers are busy processing ads. Once that queue is full, then that should create back-pressure that stops additional chains from being ingested. The size (capacity for pending chains) of the queue should probably be between 1 to 2 times the number of workers.
