### ISSUE TITLE
Measure metrics surrounding ad removal

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1590]
Captured from Slack; originally posted by @gammazero:

> We can count removal advertisements, that remove a context ID
> We can count ads that are removed because their context ID is removed by a removal ad.
> We can count these in total, or for individual providers or publishers.
> 
> Content advertisement publishers are removing ads in 3 ways:
> By publishing a removal ad to remove a context ID
> By no longer serving content when an ad’s entries chain CID is queried.
> By not longer serving advertisements

As a starting point, we should add `Counter` metrics that measure the number of removal ads vs non-removal ads.

**Comment by gammazero** [comment]
Fixed by #1591.  See: https://protocollabs.grafana.net/d/pPROWOD7z/providers?orgId=1&var-Source=storetheindex-prod&var-Jobs=storetheindex%2Findexer-single&from=now-3h&to=now&var-pod=All&viewPanel=115
