### ISSUE TITLE
Where is the handler of /routing/v1/providers/{cid}

### ISSUE THREAD

**Issue by Shawn-Huang-Tron** [ipni/storetheindex#1823]
I can't find the handler of /routing/v1/providers in code, but if i click this i can see the result output: https://cid.contact/routing/v1/providers/bafybeigvgzoolc3drupxhlevdp2ugqcrbcsqfmcek2zxiw5wctk3xjpjwy
This is handler in this repo?

**Comment by gammazero** [comment]
The handler is here: https://github.com/ipni/indexstar/blob/main/server.go#L208

indexstar is what we use for handling queries that get proxied to different backends.

**Comment by gammazero** [comment]
Closing. Reopen if this does not answer your question.
