### ISSUE TITLE
Propagate direct HTTP announces to `dev` environment for testing

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1887]
Direct announcements hit prod endpoint, which land on prod assigner. assigners flood publish direct announces over gossipsub. But none of the prod nodes are peered with dev nodes or vice versa. Therefore, dev nodes do not discover direct http announces made to prod.

Ideally, we want to also receive direct announces in `dev` (either directly or indirectly) for testing purposes.

Peering any one of the nodes with `dev` assigner should resolve this.

Note that `assigner`s do not expose a public `libp2p` port and run on separate VPCs. 

An option forward is to:
* expose `dev` assigner libp2p endpoint with a stable `dns` name.
* peer `prod` assigner to `dev` assigner.

This should result in assigner receiving direct announcements over gossipsub flood publish, which then should trigger assignments to the nodes it is responsible for.

**Comment by gammazero** [comment]
Handled in PR #1921
