### ISSUE TITLE
Change Ad schema to use `optional Link_EntryChunk`

### ISSUE THREAD

**Issue by MarcoPolo** [ipni/storetheindex#203]
Schema change suggestion in Ad:
A nil entries is currently represented as a special value, the sha256 multihash of nil. But why shouldn't we represent this as an Optional Link_EntryChunk?

Benefits:
1. We can then define the type as a `optional Link_EntryChunk` instead of Link in the schema. 
1. Clear in the schema that this can be optional.
1. Fix this surprising edge case for providers.

Downsides:
1. We have to handle both cases in storetheindex for a while.
1. Something else?

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
