### ISSUE TITLE
Concurrency issue around multiple publishers publishing ads for the same provider.

### ISSUE THREAD

**Issue by MarcoPolo** [ipni/storetheindex#205]
We currently rely on the assumption that there is a 1:1 mapping between publishers and providers. We do not guarantee this assumption anywhere. Therefore we may run into the case where we are syncing against two publishers concurrently and they provide the same chain. The behavior here isn't defined, but it's likely we'll index things in a weird order.

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
