### ISSUE TITLE
High CPU usage to the extent where the node becomes unresponsive

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#2062]
Observed on Inga on 30th of June between 0930-1130 UTC on `inga`.

Check grafana metrics, logs and investigate root cause. For now, we should not roll out 0.7.5 to prod.

**Comment by masih** [comment]
Updated the issue title as this occurs on 0.7.3 too. 

PProf/profile on the node seems to suggest locking contention with leveldb lookups
<img width="1256" alt="Screenshot 2023-06-30 at 14 14 34" src="https://github.com/ipni/storetheindex/assets/301855/384cc288-4e07-4a3d-93a5-def5ac46d371">

Which points to index counter? Investigating.

**Comment by masih** [comment]
Update: Excluding index counter from find server seems to have resolved the CPU contention. Working on a fix in #2067

**Comment by gammazero** [comment]
Fixed by #2101 and by integration of new provider cache into dhstore and indexstar.
