### ISSUE TITLE
PiKNiK having trouble querying cid.contact for a retrievable CID

### ISSUE THREAD

**Issue by TorfinnOlsen** [ipni/storetheindex#2218]
"I have an active, unsealed file 2 GB file:
Data CID: QmWPpNeWNnfBpteqTbg4UL2f19u8Vyc6eBJzFHxczVm8yo
Piece CID: baga6ea4seaqlwazchrvodnkc6etm7fhfxwrqkxchxbfocfstli7mk4eh6snhwcq
When I look this up in https://filecoin.tools/5730969 I get the information.
When I look up with CID in Boostv2 is shows indexed and active
When I go to cid.contact, I get no results."

Stu advises he allows free retrievals over graphsync

**Comment by TorfinnOlsen** [comment]
Provider command shows that their provider is caught up:

`ipni provider -i https://cid.contact/ --follow-dist \ --pid=12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1                                                                                              
cc: 
[@gammazero](https://filecoinproject.slack.com/team/U01NTMZU1HV)
 it looks to me like their provider is caught up "Provider 12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1 distance to head advertisement: 0"`

**Comment by willscott** [comment]
the remaining thing we need for this to be actionable is the CID in the 2gb file

Is `QmWPpNeWNnfBpteqTbg4UL2f19u8Vyc6eBJzFHxczVm8yo` supposed to be root of the car file in that piece?
(that's not always what we mean when we say `DataCID` though)

**Comment by willscott** [comment]
i am having trouble connecting to the provider:

```
% go run ./cmd/ipni ads list -n 1 --ai=/ip4/27.157.73.144/tcp/16090/p2p/12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1
cannot query head for sync: Get "http://unused.invalid/head": failed to dial: failed to dial 12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1:
  * [/ip4/27.157.73.144/tcp/16090] dial tcp4 0.0.0.0:51733->27.157.73.144:16090: i/o timeout
exit status 1
```

could it be that the provider failed enough times we gave up on the relevant advertisement / part of sync?

would there be a way to retry that? cc @gammazero

**Comment by gammazero** [comment]
@willscott The address you are querying for advertisements is the content retrieval address. You need to query the advertisement publishing address (`/ip4/59.59.86.88/tcp/20829`). See the `Publisher Addrs` part of the provider info.

When using the publisher address, here is what I see:
```shell
/ipni ads list -n 1 --ai=/ip4/59.59.86.88/tcp/20829/p2p/12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1
baguqeeracfh7lqfc223iej2c4qyhw4u32bqut7b3uv7rh755orbmz4q5g5iq
```
When I get the advertisement, I can see that it is a removal ad:
```shell
./ipni ads get --ai=/ip4/59.59.86.88/tcp/20829/p2p/12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1 --head
CID:          baguqeeracfh7lqfc223iej2c4qyhw4u32bqut7b3uv7rh755orbmz4q5g5iq
PreviousCID:  baguqeerathndte6ywxow44cjtclydjmdtpfxvvrbv2mp22rw7o6glgcl6beq
ProviderID:   12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1
ContextID:    AXESIB4dn5BxA1sv9uSWyCyFqDi8ds8PDYzB8t+PNx58Udqu
Addresses:    []
Is Remove:    true
Metadata :    
Extended Providers:
   None
Signature: ✅ valid
Signed by: content provider
Entries: None
```
If I get the previous ad, which is not a removal, I see this:
```shell
./ipni ads get --ai=/ip4/59.59.86.88/tcp/20829/p2p/12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1 --cid=baguqeerathndte6ywxow44cjtclydjmdtpfxvvrbv2mp22rw7o6glgcl6beq
CID:          baguqeerathndte6ywxow44cjtclydjmdtpfxvvrbv2mp22rw7o6glgcl6beq
PreviousCID:  baguqeerawdyiaq4vavff5tyc2skufjrrtu3z4p2uxkpdjttuosuj52snyeoa
ProviderID:   12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1
ContextID:    AXESIB4dn5BxA1sv9uSWyCyFqDi8ds8PDYzB8t+PNx58Udqu
Addresses:    [/ip4/192.168.31.237/tcp/16090 /ip4/127.0.0.1/tcp/16090 /ip6/::1/tcp/16090]
Is Remove:    false
Metadata :    kBKjaFBpZWNlQ0lE2CpYKAABgeIDkiAgLm64SR2m1ypENMskHFQvzSBm4rVjsCRxOVI+mwJ6gyVsVmVyaWZpZWREZWFs9W1GYXN0UmV0cmlldmFs9A==
Extended Providers:
   None
Signature: ✅ valid
Signed by: content provider
Entries:
  Chunk Count: 3
  Total Count: 36536
```

**Comment by gammazero** [comment]
When I walk back along their advertisement chain (`./ipni ads get --ai=<addr_info> --cid=<previous_cid>) I see that every advertisement that has content is always followed by a removal advertisement for the same context ID.  So, what appears to be happening is that they are deleting all the content as soon as they index it.

**Comment by LexLuthr** [comment]
There is some confusion here.
1. Stu is running Boost v2 but on minerID https://filfox.info/en/address/f01278. This minerID has a timeout problem which Graphsync fix has not helped with. This seems to be a local issue then code as other Boost v2 miners are working smoothly. 
2. The provider peerID mentioned in comment 2 belongs to a different miner (maybe PiNik) https://filfox.info/en/address/f0495421
3. The second minerID where indexes are being removed is running Boost v1.7.0 (the problematic one). So, it makes sense that they are removing the ads. 

```
boost provider libp2p-info f0495421
Provider: f0495421
Agent: boost-1.7.0+git.9da4193
Peer ID: 12D3KooWAyG2Xw86FY3XZFRzxq8pQkvVuoYnQwvAtW3PaLbCYwk1
Peer Addresses:
  /dns4/fildc-z1.yeaosound.com/tcp/16090
Protocols:
  /fil/datatransfer/1.2.0
  /fil/kad/testnetnet/kad/1.0.0
  /fil/retrieval/qry/0.0.1
  /fil/retrieval/qry/1.0.0
  /fil/retrieval/transports/1.0.0
  /fil/storage/ask/1.0.1
  /fil/storage/ask/1.1.0
  /fil/storage/mk/1.0.1
  /fil/storage/mk/1.1.0
  /fil/storage/mk/1.1.1
  /fil/storage/mk/1.2.0
  /fil/storage/mk/1.2.1
  /fil/storage/status/1.0.1
  /fil/storage/status/1.1.0
  /fil/storage/status/1.2.0
  /floodsub/1.0.0
  /ipfs/graphsync/1.0.0
  /ipfs/graphsync/2.0.0
  /ipfs/id/1.0.0
  /ipfs/id/push/1.0.0
  /ipfs/ping/1.0.0
  /legs/head/indexer/ingest/mainnet/0.0.1
  /libp2p/autonat/1.0.0
  /libp2p/balancer/forwarding/0.0.1
  /meshsub/1.0.0
  /meshsub/1.1.0
```

**Comment by gammazero** [comment]
@TorfinnOlsen Can this be closed? It looks like it was the result of using the bad version of boost.

**Comment by gammazero** [comment]
Closing, looks like a bad version of boost.
