### ISSUE TITLE
High rate of 404s from indexstar after the latest deployment

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#2277]
The rate of 404s have been at 80% since the deployement of changes [here](https://github.com/ipni/storetheindex/commit/6824c44aa70abfc4f2f874c79ad71b1e474df733)

Reverted the deployment in https://github.com/ipni/storetheindex/pull/2276

(times in UTC+1)

<img width="329" alt="image" src="https://github.com/ipni/storetheindex/assets/301855/38e417f4-1b8e-45a3-905d-6a9104dcef88">

**Comment by masih** [comment]
Confirmed reverting the changes in indexstar fixed the 404 to 200 ratio:

<img width="331" alt="image" src="https://github.com/ipni/storetheindex/assets/301855/ee69526b-9801-4d2e-afe0-0b2a7d2759e6">

**Comment by gammazero** [comment]
This was fixed by https://github.com/ipni/indexstar/pull/166
and deployed by merging #2281
