### ISSUE TITLE
Add HTTP header for Ad sync

### ISSUE THREAD

**Issue by LexLuthr** [ipni/storetheindex#2662]
As of now, all requests for CID are made on a single path /ipni/v1/ad/{CID}. The request can be for advertisement or entrylink. This basically means user need to figure out which and then try to find them. This is a waste of time and resource on provider side if they don't have the requested CID. 

To make this easier on provider implementation, can we send a HTTP header specifying this is a advertisement CID?

This will not impact any current provider implementation and would newer implementation to use this feature. Others can also upgrade if they wish. This will be limited to HTTP providers.

**Comment by gammazero** [comment]
We want to continue to use the single path `/ipni/v1/ad/{CID}` since a CID uniquely refers to a data object and in theory a provider should not need to care about what type of data a CID refers. Just return whatever object the CID identifies.

Caring about what type of data a CID refers to can be considered a provider implementation detail. Offering a hint in the form of an HTTP request header seems reasonable, and is something that can be completely ignored by implementations that do not care about what a CID references.

Suggestions:
- `IPNI-Request-Type: advertisement`
- `IPNI-CID-RefType: advertisement`

The value can be `advertisement` or `entries`

@masih, @willscott  WDYT?

**Comment by willscott** [comment]
I think this probably should be doable for the servers to specify

**Comment by willscott** [comment]
https://github.com/ipni/go-libipni/blob/main/dagsync/ipnisync/sync.go#L305 is around where the header would be needed, but there's some threading of whether we're doing that in the context of advertisements or entries since the same fetch method is used in both cases.

**Comment by gammazero** [comment]
When the subscriber creates the syncer, which is created for an ad chain sync or an entries chain sync, it can set the optional type hint in `NewSyncer` here: https://github.com/ipni/go-libipni/blob/main/dagsync/ipnisync/sync.go#L101

So no need to thread it through the function args.

**Comment by masih** [comment]
I would make this optional and a hint header. Something like: `X-Ipni-Cid-Schema-Type`

**Comment by masih** [comment]
> then try to find them. This is a waste of time and resource on provider side if they don't have the requested CID.

Note that the expense of looking this up is entirely dependent on how the content addressable data (i.e. IPNI ads) are stored. It so happens that this is expensive in the current SP setup. Hence the suggestion for optional hint header above.

I would also move this issue to specs repo.

**Comment by gammazero** [comment]
Optional, definitely.  How about `Ipni-Cid-Schema-Type`? The `X-` prefix is so [pre-2012](https://datatracker.ietf.org/doc/html/rfc6648).

**Comment by masih** [comment]
> So no need to thread it through the function args

In terms of implementation, set as value in `context` that gets passed around to syncer?

**Comment by gammazero** [comment]
I would prefer not, because the same context may be used across both the ad and the entries syncer and that means creating separate derived context. I prefer to set the hint when each syncer is created.

**Comment by masih** [comment]
> The `X-` prefix is so [pre-2012](https://datatracker.ietf.org/doc/html/rfc6648).

In a world where most people live in the future, it takes courage (and lack of keeping up with IETF) to live in the past 😄

**Comment by gammazero** [comment]
Agree. FYI I just ran across RFC-6648 in the last couple weeks myself.

**Comment by gammazero** [comment]
Well, it turns out my assumptions we incorrect and it does seem best to set a value in context that gets passed around to syncer.
