### ISSUE TITLE
Allow-list to accept advertisements on behalf of other publishers.

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#294]
it should be possible for one component that has one key pair to generate advertisements saying that another libp2p host has content.
We may not want to allow this by default, and currently [require](https://github.com/filecoin-project/storetheindex/blob/main/api/v0/ingest/schema/envelope.go#L132) these two concepts of identity to be the same.
It would be good to have a mechanism to allow for more flexibility here, and support two use cases:
* A given provider A can sign an advertisement chain saying that a publisher B has content. We want to have an allow list saying (A allowed for B)
* A given provider A can sign an advertisement chain saying that a collection of publishers (B, B',...) have content.
* A given provider A can sign an advertisement chain saying that any publisher has content.

**Comment by masih** [comment]
Relates to https://github.com/filecoin-project/storetheindex/issues/257

**Comment by ischasny** [comment]
Yeps, thanks @gammazero. Looks like there a bunch of related issues here.

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
