### ISSUE TITLE
Handle multiple publisher addresses

### ISSUE THREAD

**Issue by gammazero** [ipni/storetheindex#321]
Announce messages may have multiple publisher addresses.  Sync should accept multiple addresses and use them instead of only using a single address.

`dagsync/dtsync` and `dagsync/httpsync` should both make use of multiple publisher addresses.

If there are multiple publisher addresses for a provider, use the addresses for auto-sync until a working address is found.

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
