### ISSUE TITLE
Investigate how to generate deterministic peer IDs using a secret Seed

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#328]
Instead of generating peer identities at random per indexer, see how we can have a secret seed that then identities can be generated from. This way we can reduce manual step of generating identity and checking it into code when scaling out indexers.

_Originally posted by @MarcoPolo in https://github.com/filecoin-project/storetheindex/issues/327#issuecomment-1089134448_

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
