### ISSUE TITLE
Configure CloudFlare using Infrastructure as code

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#378]
CloudFlare configuration is currently done via clicking in the UI, with output from terraform copy pasted. 

Define CouldFlare configuration in Terraform and have that call the CloudFlare APIs so that:
1. it is clear what we intend the configuration in CloudFlare to be.
2. changes to it are reviewed.
3. there is an audit trail of it.
4. we can avoid accidental human errors.

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
