### ISSUE TITLE
keep synced ingest chains as ipld blocks for archival purposes

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#381]
currently chains are fully synced with legs into temporary block stores, and then processed.
We should also archive a log of car files with ingested blocks, and begin a pipeline of archiving those car files.

Access to the blocks will allow short-circuiting of provider re-ingest, and can provide more reliable startup mechanisms for subsequent indexers

**Comment by TorfinnOlsen** [comment]
@willscott would you say the scope of our indexer scalability work sufficiently covers this capability?

**Comment by masih** [comment]
This is done by https://github.com/ipni/storetheindex/pull/1277
