### ISSUE TITLE
Update "Uptime In Seconds" Graph Per Pod

### ISSUE THREAD

**Issue by davidd8** [ipni/storetheindex#394]
Update the "Uptime in Seconds" Graph to show all instances' uptime in one chart to give a better sense of uptime. Currently, the graph only shows uptime per instance, not for the entire pod. 
<img width="621" alt="Screen Shot 2022-04-18 at 3 31 15 PM" src="https://user-images.githubusercontent.com/390075/163887881-65906f91-4859-4e18-8960-5885be205f7e.png">

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
