### ISSUE TITLE
indexer cache of of ingested blocks

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#411]
The data fetched by the indexer while ingesting from providers is currently downloaded into temporary block stores. these are then cleaned up after they are fully pulled and data is processed.

We should have a single blockstore view over this imported data, and allow a policy to cleanup not simply when ingest finishes, but rather based on either a target size, or a target caching time for blocks (e.g. either 'i want to keep ingested blocks around for 1 day', or 'i want to keep up to 500gb of ingested blocks around')

**Comment by masih** [comment]
Deferred while experimenting with IPFS-based caching. See https://github.com/filecoin-project/storetheindex/discussions/446

**Comment by TorfinnOlsen** [comment]
Closing due to a lack of activity > 6 months
