### ISSUE TITLE
Mechanism design for participation

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#456]

**Comment by gammazero** [comment]
- Explicit configuration of peer indexers, or discovery via gossip pubsub on federation-ID topic.
  - Explicit ID enables message signing and can exclude unknown indexers.
- What info to exchange
  - Providers
  - Cache nodes
  - Keyspace assignments
- How to exchange data with peers
  - Push, pull, broadcast

**Comment by gammazero** [comment]
Replaced by #465
