### ISSUE TITLE
Double-hashing / content privacy enhancements

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#458]

**Comment by TorfinnOlsen** [comment]
@ischasny is this a duplicate issue or still the main issue tracking the entirety of double hashing efforts? If it's the right container I'll remediate any others I come across!

**Comment by ischasny** [comment]
@TorfinnOlsen  Probably that would be the main one - at least it's the only one I could find.

**Comment by gammazero** [comment]
Double hashing is done exclusively in our indexer deployments. Calling this done and closing. Open new issues for specific enhancements.
