### ISSUE TITLE
Indexer can use IPFS as index content cache

### ISSUE THREAD

**Issue by gammazero** [ipni/storetheindex#467]

**Comment by gammazero** [comment]
When advertisements are received, an indexer can store advertisements and multihash entry blocks in IPFS. Other indexers can retrieve these advertisements and entry blocks from IPFS instead of fetching them directly from the index provider.

**Comment by honghaoq** [comment]
https://github.com/ipfs-shipyard/go-ds-remote-ipfs

**Comment by TorfinnOlsen** [comment]
@gammazero is this still applicable to our long term intents for cross indexer synchronization?

**Comment by gammazero** [comment]
This is not directly applicable. We may want to put the contents of a content advertisement mirror (car files) into IPFS, maybe as a way to pull the car files into a deployment from a non-local mirror. That seems like more of a infrastructure/ops decision and not within the scope of indexing.

Closing for now.
