### ISSUE TITLE
Planning: capability to skip deals for Indexing

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#476]
@gammazero @willscott we were discussing this in the call with SPs, this is a common ask, I couldn't find this work in our backlog so added an issue, can you comment on the plan here - do we plan to work on it this quarter?

**Comment by willscott** [comment]
we continue to hold pretty firm that this is a markets issue and not an indexing issue. If that content is available for retrieval but not in the index, then we are misrepresenting its state to providers. The content needs to be made not available for retrieval at the same time that it is not published to the index.

**Comment by honghaoq** [comment]
Yes, opening it to track this issue, Mayank discussed with Jennifer and decided the best step is to have a discussion to settle on requirement that applies across Lotus / Boost / Venus implementations. I will open a discussion thread on github for this matter.

**Comment by honghaoq** [comment]
Will be opening a FIP discussion thread as suggested by @LexLuthr and @jennijuju

**Comment by honghaoq** [comment]
https://github.com/filecoin-project/FIPs/discussions/376

**Comment by TorfinnOlsen** [comment]
This capability was added to boost with a flag which enables them to not advertise deals to the indexer.
