### ISSUE TITLE
Report errors on full disk

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#484]
Ken labs reports:
the STI process hangs and no related errors are reported when disk space is used up

**Comment by gammazero** [comment]
With indexer freeze functionality, each indexer logs its disk usage at every check:
```
INFO    Disk usage OK   {"usage": "0.13%", "freezeAt": "90%"}
```
When it is within 10% of reaching the freeze threshold, a warning is logged:
```
WARN    Disk usage ALERT     {"usage": "81.77%", "freezeAt": "90%"}
```
When it is within 2% of reaching the freeze threshold, a critical warning is logged:
```
WARN    Disk usage CRITICAL  {"usage": "88.45%", "freezeAt": "90%"}
```
The usage checks and log messages become more frequent as usage approaches the freeze point.

**Comment by gammazero** [comment]
These log entries should serve as a sufficient warning for full disk.
