### ISSUE TITLE
`TestPollProviderOverrides` fails intermittently on Windows

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#508]
Failed in [this](https://github.com/filecoin-project/storetheindex/runs/6560285319?check_suite_focus=true#step:24:452) build but the [rerun](https://github.com/filecoin-project/storetheindex/runs/6560447563?check_suite_focus=true#step:7:543) of the same commit passed.

Test logs from the failed build:
```
=== RUN   TestPollProviderOverrides
    registry_test.go:625: should not have valid publisher after polling stopped
--- FAIL: TestPollProviderOverrides (0.01s)
```

**Comment by masih** [comment]
At times it seems to fail intermittently with this error too :
```
registry_test.go:637: sync channel should not have beem written to for override peer
```

**Comment by gammazero** [comment]
Fixed by accounting for lower resolution (millisecond) timers on Windows.
