### ISSUE TITLE
Ingest test fails intermittently when run with race detector

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#614]
Build [failing](https://github.com/filecoin-project/storetheindex/runs/7609417484?check_suite_focus=true#step:9:670) on a commit that only bumped version file, which then [passed](https://github.com/filecoin-project/storetheindex/runs/7609545516?check_suite_focus=true) on the second run.

**Comment by gammazero** [comment]
This happens because the `WaitGroup.Add` called [here](https://github.com/filecoin-project/go-legs/blob/main/subscriber.go#L842) if being called concurrently with the `WaitGroup.Wait` [here](https://github.com/filecoin-project/go-legs/blob/main/subscriber.go#L348).

**Comment by gammazero** [comment]
Likely fixed by moving to from legs dagsync
