### ISSUE TITLE
Deploy before end of previous rolling deploy doesn't apply

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#624]
We merged https://github.com/filecoin-project/storetheindex/pull/623 while https://github.com/filecoin-project/storetheindex/pull/620 had completed scanning an initial replica but was not fully applied.

a day later, dev.cid.contact health indicates it hasn't applied the newer merge and is still on #620

**Comment by TorfinnOlsen** [comment]
looks like both dependencies for this issue were merged closing this out.
