### ISSUE TITLE
Pinata publish to Indexer and run indexer node

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#630]
1. Move to elastic IPFS
2. Provide index (to public indexer)
Once on elastic, use the same index providing mechanism to provide IPFS index - https://github.com/elastic-ipfs/publisher-lambda/tree/main/src/handlers
3. Run Indexer node

**Comment by honghaoq** [comment]
Note: more helpful for Pinata to provide to public indexer instead of private one -
the current DHT is crawl-able, and if they’re making the data accessible in the current IPFS network the expectation is that they’re announcing it publicly already.

**Comment by gammazero** [comment]
This no longer appears to be an actionable item for this team.
