### ISSUE TITLE
Not properly using advertisement announce address over ad containing provider address when both specified

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#639]
```
beginning sync of 12D3KooWQoUeEjqcxFf59Mfw2xmdMCNFm49Cwqy63mXKs7GtimKh
  * [/ip4/54.148.129.148/tcp/3000/ws] failed to negotiate stream multiplexer: protocol not supported
  * [/ip4/52.40.174.99/tcp/3000/ws] failed to negotiate stream multiplexer: protocol not supported
```

we've lost the http endpoint of the records and are using the multiaddrs contained in them.

**Comment by gammazero** [comment]
The announce address (publisher address) will always be used unless there was no publisher address supplied by an announce message, as may be the case with a manual sync using the (wrong) provider address.

I think this is fixed, unless we see this happening again.
