### ISSUE TITLE
Resume ingest from already downloaded chain instead of re-downloading

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#691]
The ingest process downloads the chain first before processing the ad entries. This is to guarantee that ads are processed in the right order. In a case where the chain is very long, it could take days for the chain to be downloaded. When the ad entry processing fails the ingest process will stop until either a manual sync is triggered, an announcement is received or there is a queued announcement for that provider.

When the processing starts back up again it attempts to re-download the chain from the head, stopping at the **latest processed ad**; see [`syncHandler`](https://github.com/filecoin-project/storetheindex/blob/6274938438f159acd5d46f0c97666c9f86ee796f/internal/ingest/synchandler.go#L21). This means the unprocessed portion of the chain will be re-downloaded.

Ideally, the ingestion mechanism should differentiate between downloaded and unprocessed ads to improve end to end ingest latency in such failure case.

**Comment by masih** [comment]
For HTTPsync a CID is only downloaded if it is not locally present. For DTsync the work [here ](https://github.com/filecoin-project/go-legs/pull/155) should avoid redownloading blocks already present in local datastore

**Comment by TorfinnOlsen** [comment]
@masih I believe we still want to accommodate this if we haven't already it seems like a great efficiency win(not sure how frequently this ad ingestion fails but it seems like something that could really stack up. Should I keep this open, or look deeper into whether or not we should make room for this work in our backlog?

**Comment by masih** [comment]
I think we should keep this open an put it on the backlog: in terms of priority it is lower in the list and overlaps with ad ingest from CAR files that @gammazero is working on.

**Comment by gammazero** [comment]
This was fixed by:
https://github.com/ipni/go-libipni/pull/62
and
#2004
