### ISSUE TITLE
Blog post on Index providing

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#715]
Honghao to work with @masih on this https://www.notion.so/pl-strflt/How-to-be-an-Index-Provider-d2c3b167eb8145cb9e089ac6481be480

**Comment by gammazero** [comment]
No movement on this. If this issue still exists, a new one should be opened as an IPNI documentation issue.

**Comment by masih** [comment]
This is ongoing sttill

**Comment by masih** [comment]
The writeup is ready for review.

**Comment by TorfinnOlsen** [comment]
Posted to rave reviews! https://filecoin.io/blog/posts/how-to-be-an-index-provider/
