### ISSUE TITLE
Kubo-Reframe integration to publish index

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#720]
Tracking item for PM, actual issue at kubo repo: https://github.com/ipfs/kubo/issues/9186 
- For adding reframe provide RPC: Will
- For Reframe code review / general support: Ivan & Antonio

**Comment by ischasny** [comment]
Hi @honghaoq. This is being implemented here: https://github.com/ipfs/kubo/pull/9274.

**Comment by gammazero** [comment]
@ischasny If this is done, please close
