### ISSUE TITLE
Slingshot program use index providing as requirement with validation in place

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#724]
Done criteria: Validate index providing mechanism implemented on slingshot and verify on indexer with 20% Filecoin deal coverage (deal coverage of slingshot program)

**Comment by TorfinnOlsen** [comment]
Have consistently surpassed 20% Filecoin deal coverage

**Comment by gammazero** [comment]
Deal coverage has been stable at above 40%.  This is being tracked on the IPNI filecoin grafana dashboard.
