### ISSUE TITLE
Unable to have clean/fast shutdown when indexing

### ISSUE THREAD

**Issue by gammazero** [ipni/storetheindex#738]
When sending SIGINT to the daemon it should perform a graceful shutdown. This does not happen when the daemon is busy indexing ad chains. Instead, the daemon waits for operations to complete and must eventually be killed.  This risks not saving data to the value store consistently and makes a subsequent fast startup impossible.

This is likely really a go-legs issue, but it affects the storetheindex daemon.

**Comment by masih** [comment]
Question: how much would clean shutdown matter for value stores other than sth?

**Comment by gammazero** [comment]
It depends on size and whether they care about fast startup.  Only with a clean shutdown can memory state be safely saved, which is what enables to very fast (1 or 2 second) startup.

**Comment by TorfinnOlsen** [comment]
@gammazero considering that we're not leveraging go-legs or atleast no longer want to support it would it make sense to go ahead and close this issue out as unplanned?

**Comment by gammazero** [comment]
At this point, this appears fixed due to #1385 and a change in #1449 that does not wait forever for data-transfer manager to stop.
