### ISSUE TITLE
Increase upper limit for `prod-ue2-m4-xl-2` worker node ASG

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#768]
The `prod-ue2-m4-xl-2` worker node group  [here](https://github.com/filecoin-project/storetheindex/blob/main/deploy/infrastructure/prod/us-east-2/eks.tf#L32) has the upper limit of `7` currently. Increase that to 10 and apply the changes to prod.

Note that changes to terraform needs to be applied manually. So create a PR with the changes proposed above, and add the output of `terraform plan` as a PR comment. Once the PR is approved go ahead and run `terraform apply` before merging the branch.

**Comment by gammazero** [comment]
This appears to already be done or not applicable as the prod-ue2*-m4-xl nodes have max_size set to 10, and there are no prod-ue2-m4-xl-2 nodes.
