### ISSUE TITLE
Add indexer pointer on ipfs site

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#794]
Adding Indexer pointer here: https://docs.ipfs.tech/concepts/#peer-to-peer-file-sharing

Issue link in ipfs-doc: https://github.com/ipfs/ipfs-docs/issues/1296

**Comment by TorfinnOlsen** [comment]
Test comment

**Comment by gammazero** [comment]
Indexers, as they relate to IPFS, are documented in delegated routing documentation.
