### ISSUE TITLE
`TestAnnounceIsDeferredWhenProcessingAd` causes intermittent race condition that fails some runs with race detector 

### ISSUE THREAD

**Issue by ischasny** [ipni/storetheindex#829]

**Comment by gammazero** [comment]
Looks like this also happens with `TestAnnounceIsNotDeferredWhenProcessingAd`. Example [here](https://github.com/filecoin-project/storetheindex/actions/runs/3158634520/jobs/5140886056).

**Comment by gammazero** [comment]
No longer happening. Maybe fixed.
