### ISSUE TITLE
Manual sync from previously unknown peers fail with `no good addresses`

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#865]
When a provider over datatransfer is completely unknown to the indexer, manual sync seems to fail with `no good addresses` error. This is because the datatransfer libp2p host peerstore is not updated with the address from the explicit sync and therefore the host fails to connect.

Update the libp2p peerstore with the address provided via the sync command before manual sync.

**Comment by gammazero** [comment]
I have not observed this and can do a manual sync with a previously unknown publisher.  Check that you are not using an unroutable local network address, or set `Discovery.FilterIPs` to `false`.

**Comment by masih** [comment]
I observed this on all nodes except indexer 0 and 1 on prod. I confirmed that peerstore is an issue by adding the peer multiaddr to the bootstrap list. After that the sync started working.

This should be straightforward to reproduce.

**Comment by masih** [comment]
OK this is happening again; here is a concrete address example:

```
{"level":"error","ts":"2022-09-30T12:23:10.947Z","logger":"indexer/ingest","caller":"ingest/ingest.go:415","msg":"Failed to sync with provider","provider":"12D3KooWDtiA9w5c37MnFpGWr2M12m8neoUqDroHEMsJVuf3ELi7","peerAddr":"/ip4/195.167.147.43/tcp/9999/p2p/12D3KooWDtiA9w5c37MnFpGWr2M12m8neoUqDroHEMsJVuf3ELi7","depth":0,"resync":false,"err":"cannot query head for sync: Get \"http://unused.invalid/head\": no good addresses. Possibly incorrect topic configured"}
```

I am going to pick this up next.

**Comment by masih** [comment]
After having spoken with Andrew, reducing priority of this to P3 because nodes seem to recover from it after a while and I can't reproduce this locally.

Logs from nodes on which this occurred [here](https://protocollabs.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Benvironment%3D%5C%22prod%5C%22,%20namespace%3D%5C%22storetheindex%5C%22%7D%20%7C~%20%5C%22no%20good%20addresses%5C%22%5Cn%5Cn%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221664406000000%22,%22to%22:%221664578799000%22%7D%7D).

**Comment by masih** [comment]
This is happening again on dev right now

**Comment by gammazero** [comment]
The `admin sync` command fails always when the address contains a libp2p ID. Could this be the problem that the publisher address contains a libp2p ID?

Example command that fails always:
```
./storetheindex admin sync --pubid 12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC --addr /ip4/209.94.92.6/tcp/24001/p2p/12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC
```
The error in the indexer logs is:
```
ERROR   indexer/admin   http/handler.go:299     Cannot sync with peer   {"peerID": "12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC", "address": "/ip4/209.94.92.6/tcp/24001/p2p/12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC", "err": "failed to sync: cannot query head for sync: Get \"http://unused.invalid/head\": no good addresses. Possibly incorrect topic configured"}
```
The command without the p2p ID in the address works alwaya:
```
./storetheindex admin sync --pubid 12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC --addr /ip4/209.94.92.6/tcp/24001
```

**Comment by masih** [comment]
Thank you for pointing this out Andrew, I am trying to understand why the sync addr that includes ID sometimes succeeds. I think if there is a connection already open to the peer then the sync with addr that contains ID works but not if the connection has been terminated. 

hank you for sorting this out by filtering the ID.
