### ISSUE TITLE
Error analysis of failed retrieval requests with indexer candidates

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#945]
Understanding the gap from requests with indexer candidates to requests with successful queries. Ideal outcome could be a sorted error/issue list to give a breakdown view of the failed queries, so indexer team can take a look and followup from there.

https://protocollabs.grafana.net/d/G6kN_v27k/autoretrieval-bridge?orgId=1&refresh=5s&from=now-30d&to=now

**Comment by rvagg** [comment]
Related https://github.com/application-research/autoretrieve/issues/137

**Comment by honghaoq** [comment]
Related notion https://www.notion.so/pl-strflt/Autoretrieval-bridge-retrieval-funnel-256571f3eb5c439aa099336017daba57

**Comment by honghaoq** [comment]
@rvagg any update over here

**Comment by gammazero** [comment]
IPNI ingestion dashboard, fed by telemetry service, shows ingestion errors broken down by type. This allows drill-down into logs and provider information to determine which providers have which errors and why.

Considering this fixed.
