### ISSUE TITLE
Find on prod `indexer-0` and `indexer-1` is very slow

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#951]
[Since adding](https://github.com/filecoin-project/storetheindex/pull/950) `indexer-0` and `indexer-1` to prod `storetheindex` there are high spikes in upstream latency, caused by slow lookups on those two nodes:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/301855/197187733-50dd2bdb-c94c-4da0-bd46-7ab04f19fd7e.png">

<img width="749" alt="image" src="https://user-images.githubusercontent.com/301855/197187819-6b675a83-28fa-4370-b7d7-1c79f4d504f1.png">

Seeing a lot of the following in the logs:

```
"{\"level\":\"error\",\"ts\":\"2022-10-21T11:20:53.815Z\",\"logger\":\"indexer/http\",\"caller\":\"httpserver/util.go:29\",\"msg\":\"Cannot handle request\",\"regType\":\"get\",\"err\":\"failed to query \\\"1220b9a0b2f5276ce458b0bc3f122a89fe1d5700ca95b1d897cfbec14964bdb6bd89\\\": cannot get values for multihash: cannot get value: multihash length inconsistent: expected 65; got 67\",\"status\":500}\n"
```
[Logs](https://protocollabs.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Benvironment%3D~%5C%22prod%5C%22,%20namespace%3D~%5C%22storetheindex%5C%22,%20pod_name%3D~%5C%22indexer-.%2A%5C%22%7D%20%7C~%20%5C%22error%5C%22%20%7C~%20%5C%22http%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221666347083237%22,%22to%22:%221666352427026%22%7D%7D).

**Comment by gammazero** [comment]
No longer applies.  Indexers moved to pebble.
