### ISSUE TITLE
Revise CID count estimation

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#982]
The current estimate of number of CIDs ingested by storetheindex is backing store dependant. It is made up of the size of index [divided by a constant ](https://github.com/filecoin-project/storetheindex/blob/main/server/finder/handler/finder_handler.go#L140) as a reasonable estimate of a single CID size. This approach can result in high discrepancy if applied to nodes that use different backing stores which take advantage of things like compression.

Retiring old nodes with larger index size will cause the CID count estimate to fluctuate, which may be confusing for the users. At the same time, iterating over the existing indices just to make an accurate count of the number of CIDs ingested seems cumbersome with little reward. Problem remains that we do need to make a better estimate of the number of CIDs ingested reported on cid.contact.

Ways forward:
1. take the current number as the offset, and add a counter to the nodes to report count going forward. Then report the number of CIDs as offset plus current accurate count.
   * Doesn't require much engineering and won't cause dramatic fluctuation in the current value reported but will result in a less accurate estimate of total number of indexed records.
2. Take a snapshot of the most up-to-date node state, attach it on a counter implementation that iterates over the records and returns an accurate count. At the same time implement a counter that starts counting going forward. Once the counter on snapshot finishes, add the resulting value to the new count and we then should have an accurate number.
   * This will give us an accurate number of indexed records but will come with potential fluctuation (most likely decrease) of the value reported today.

My current thought is to proceed with  option No. 1 considering the other work at hand.

Cc @honghaoq

**Comment by honghaoq** [comment]
Thanks Masih, I like #1, it is useful to have a more consistent (less jumpy) overall CID count estimation, but probably not worth it to spend a ton of engineering effort just to get a super accurate count.

**Comment by honghaoq** [comment]
@masih do we end up agreeing to go with option 1 here, is there an ETA for the update? From our call last time I think in Q4 - End of Dec?

**Comment by masih** [comment]
Based on further discussion we are going to add a delta calculation metric that reports the number of currently indexed hashes instead of an absolute "total ingested". That is a more useful metric that would go up and down as indices are added and removed

**Comment by LaurenSpiegel** [comment]
Would it be possible to do option 1 plus a low lift accuracy adjustment to the current count? Basically adjust the constant for each indexer by what we see the actual size increase for new CID's added to that indexer. So, if we see from the new counter that 100 CID's are added and storage space increased by X, we average that on that indexer, each index takes up X/100. Feel free to tell me this is a bad idea.

**Comment by willscott** [comment]
discussed with @masih to plan to start with option 1.

I think the real question around what is the 'current count' is that there are multiple replicas right now that are partially overlapped, so getting a true absolute count isn't particularly obvious. we'll start with the deltas and a very rough guess around current overall count.

**Comment by masih** [comment]
I have spent some time today experimenting with how to get this out of Pebble-backed stores. I have introduced a `Stats` API to the internals of indexer store [here](https://github.com/filecoin-project/go-indexer-core/pull/115) which offers a pretty close enough estimation of "unique mutlihashes indexed".  once merged, i'll use that API to replace the current "Total CIDs Indexed" on cid.contact, which dropped significantly since we retired the last remaining STH-backed node.

**Comment by masih** [comment]
Thanks to @gammazero we have metrics in place that would measure an accurate count of total CIDs once the advertisements are reinvested. 

No engineering work remains here. Though let's keep this issue open until ad reingest is complete and accurate count is measured.

**Comment by gammazero** [comment]
CID counts need to be determined on DHStore nodes, if at all, since GC deletes CIDs and
